# Generated by Django 5.0.4 on 2024-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_read', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvupload',
            name='image',
        ),
        migrations.AddField(
            model_name='csvupload',
            name='csv',
            field=models.FileField(default='default.csv', upload_to='uploaded_csv/'),
        ),
    ]
