# Generated by Django 5.0.4 on 2024-06-08 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_read', '0002_remove_csvupload_image_csvupload_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='csv',
            field=models.FileField(upload_to='uploaded_csv/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
